from django.urls import path
from .views import (
    UploadAndProcessView,
    GetResultsView,
    ExportResultsView,
    GenerateReportView,
    GetGeographicalDataView,
    GetClusterDetailsView,
    GetEvaluationMetricsView,
    GetSilhouettePlotView,
    DownloadPDFReportView,
    DownloadSampleExcelView,
)


urlpatterns = [
    path(
        "clustering/upload/", UploadAndProcessView.as_view(), name="upload-and-process"
    ),
    path(
        "clustering/results/<uuid:session_id>/",
        GetResultsView.as_view(),
        name="get-results",
    ),
    path(
        "clustering/export/<uuid:session_id>/",
        ExportResultsView.as_view(),
        name="export-results",
    ),
    path(
        "clustering/report/<uuid:session_id>/",
        GenerateReportView.as_view(),
        name="generate-report",
    ),
    path(
        "clustering/geography/<uuid:session_id>/",
        GetGeographicalDataView.as_view(),
        name="get-geographical-data",
    ),
    path(
        "clustering/cluster/<uuid:session_id>/<int:cluster_id>/",
        GetClusterDetailsView.as_view(),
        name="get-cluster-details",
    ),
    path(
        "clustering/evaluation/<uuid:session_id>/",
        GetEvaluationMetricsView.as_view(),
        name="get-evaluation-metrics",
    ),
    path(
        "clustering/silhouette-plot/<uuid:session_id>/",
        GetSilhouettePlotView.as_view(),
        name="get-silhouette-plot",
    ),
    path(
        "clustering/silhouette-plot/<uuid:session_id>/<str:year>/",
        GetSilhouettePlotView.as_view(),
        name="get-silhouette-plot-year",
    ),
    path(
        "clustering/download-pdf/<uuid:session_id>/",
        DownloadPDFReportView.as_view(),
        name="download-pdf-report",
    ),
    path(
        "clustering/sample-excel/",
        DownloadSampleExcelView.as_view(),
        name="download-sample-excel",
    ),
]
